### ISSUE TITLE
A question about motion vector

### ISSUE THREAD

**Issue by xizaoqu** [jy0205/LaVIT#28]
Hi, I visualize the extracted motion vector by mv-extractor, it seems kind of noisy, will it influence the training and validation performance of video generation?

https://github.com/jy0205/LaVIT/assets/45515569/afd99d47-d9dc-4581-9ebb-1b7cc9225803

![test3](https://github.com/jy0205/LaVIT/assets/45515569/c147ee2d-7ebd-407b-beee-49d93461dda3)

**Comment by jy0205** [comment]
Compared to dense optical flow, the motion vector is a sparser representation (motion representation of 16x16 pixel macro-blocks, rather than each pixel, so may be kind of noisy); According to our experimental conclusions, using motion vector is enough to serve as a strong condition to reconstruct the original video.

**Comment by xizaoqu** [comment]
Thanks for your reply.
